// Generated by tools/generate_pet_sprite_asset.py.
// Repository default pet: Alice.

#pragma once

#include <Arduino.h>
#include <pgmspace.h>

constexpr uint8_t kCodexPetFrameWidth = 72;
constexpr uint8_t kCodexPetFrameHeight = 78;
constexpr uint16_t kCodexPetFramePixels =
    kCodexPetFrameWidth * kCodexPetFrameHeight;
constexpr uint8_t kCodexPetFrameCount = 57;
constexpr uint16_t kCodexPetTransparentColor = 0x1FF8;

extern const uint16_t
    kCodexPetFrames[kCodexPetFrameCount][kCodexPetFramePixels] PROGMEM;

extern const uint8_t kCodexPetIdleFrames[] PROGMEM;
extern const uint16_t kCodexPetIdleDurations[] PROGMEM;
extern const uint8_t kCodexPetRunningRightFrames[] PROGMEM;
extern const uint16_t kCodexPetRunningRightDurations[] PROGMEM;
extern const uint8_t kCodexPetRunningLeftFrames[] PROGMEM;
extern const uint16_t kCodexPetRunningLeftDurations[] PROGMEM;
extern const uint8_t kCodexPetWavingFrames[] PROGMEM;
extern const uint16_t kCodexPetWavingDurations[] PROGMEM;
extern const uint8_t kCodexPetJumpingFrames[] PROGMEM;
extern const uint16_t kCodexPetJumpingDurations[] PROGMEM;
extern const uint8_t kCodexPetFailedFrames[] PROGMEM;
extern const uint16_t kCodexPetFailedDurations[] PROGMEM;
extern const uint8_t kCodexPetWaitingFrames[] PROGMEM;
extern const uint16_t kCodexPetWaitingDurations[] PROGMEM;
extern const uint8_t kCodexPetRunningFrames[] PROGMEM;
extern const uint16_t kCodexPetRunningDurations[] PROGMEM;
extern const uint8_t kCodexPetReviewFrames[] PROGMEM;
extern const uint16_t kCodexPetReviewDurations[] PROGMEM;
